language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
env:
  - CXX=g++-4.8
before_script:
  - npm install grunt-cli -g
script:
  - npm test
  - grunt build
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
